### ISSUE TITLE
Improve Handling of Portfolio Data & Calculations

### ISSUE THREAD

**Issue by cschmidli** [OFBDABV/SBTi#220]
it's currently a bit confusing how the portfolio data/calculation is handled & managed.

1. the function [get_data(...)](https://github.com/OFBDABV/SBTi/blob/master/SBTi/utils.py#L142) in utils.py is taking a list of DataProvider and PortfolioCompany and then just returns a data frame.
1. this data frame is then later used in the Temp Score calculations, even though there you could also use it without the portfolio data. And if I understand it correctly, temp score calculations on a company level don't need any portfolio data, so it feels like you're mixing stuff here.

What could be improved: 

- better separate the computations around aggregated data for portfolios from the calculations of temp scores. One is the temp score on a company level and one is on portfolio level
- have more clear input for the function that combines Company, Target and Portfolio data. Right now it needs a provider, even though the actual input you need at this stage is the calculated temp scores on company level, and then just join in more portfolio data for further aggregations
- if you want to keep that you need to pass a Provider as input to this function, maybe it would make sense to add a provider that actually takes directly the class Company and Target as inputs, rather than it has to be CSV or Excel. Though I still feel like the input for the portfolio agg functions should be the temp score on company level plus whatever extra data is needed on a company level, rather than the provider again.

does it make sense?

**Comment by ofjpostema** [comment]
Currently, what happens in the get_data method is that for each company in the portfolio, all targets and company info are retrieved. For this, all data providers are used in a "waterfall" fashion, which is why we need a list of data providers (i.e. if data provider A doesn't have the required information, we'll ask data provider B). These targets are then denormalized and a 9-box grid is created, as per the Target Validation Protocol from the SBTi's methodology. Therefore this step is essential and I don't see how could do this in separate steps.
The information in the portfolio data is also included in this denormalized data set as some of the fields in the portfolio might be required during the calculation of the temperature score (mainly "engage_target").

To make the notebooks cleaner, I've now added the option to perform the data retrieval in the calculate method, so the user doesn't need to know what's happening under the hood and can just pass-in his data providers and portfolio.
